// PM2 Ecosystem Configuration
// Auto-generated by Wingman - do not edit manually
module.exports = {
  "apps": [
    {
      "name": "swift-zinnia-forge-app-off-piste-studio",
      "namespace": "wingman-apps",
      "script": "bash",
      "args": [
        "-c",
        "set -a; [ -f .env ] && . ./.env; set +a; export APP_ID='a54f297c-c139-4f53-8f0d-0350e586ad1b' APP_LABEL='Off Piste Studio' USER_ALIAS='swift-zinnia-forge' PORT=41011; npm run dev"
      ],
      "cwd": "/home/pw21/wingman/swift-zinnia-forge/off-piste-studio",
      "out_file": "/home/pw21/wingman/swift-zinnia-forge/off-piste-studio/apps/logs/swift-zinnia-forge-app-off-piste-studio-out.log",
      "error_file": "/home/pw21/wingman/swift-zinnia-forge/off-piste-studio/apps/logs/swift-zinnia-forge-app-off-piste-studio-error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs": true,
      "autorestart": false,
      "max_restarts": 0,
      "min_uptime": "5s"
    },
    {
      "name": "swift-zinnia-forge-editing-off-piste-studio-6a5c384e",
      "namespace": "wingman-agents",
      "script": "bash",
      "args": [
        "-lc",
        "unset OPENAI_BASE_URL OPENAI_API_KEY CODEX_API_KEY ANTHROPIC_BASE_URL ANTHROPIC_API_KEY OPENROUTER_HOST OPENROUTER_API_KEY GOOSE_PROVIDER; exec '/home/pw21/code/wingman/out/agentapi' 'server' '--port' '3704' '--allowed-origins' '*' '--allowed-hosts' 'localhost,127.0.0.1,[::1],dev.otherstuff.studio,dev.otherstuff.ai' '--' 'claude' < /dev/null"
      ],
      "cwd": "/home/pw21/wingman/swift-zinnia-forge/off-piste-studio",
      "env": {
        "SESSION_ID": "6a5c384e-2bc6-4208-8a27-b3cff5d848a6",
        "SESSION_NAME": "editing Off Piste Studio",
        "SESSION_PORT": "3704",
        "SESSION_DIRECTORY": "/home/pw21/wingman/swift-zinnia-forge/off-piste-studio",
        "SESSION_AGENT": "claude",
        "USER_ALIAS": "swift-zinnia-forge",
        "WINGMAN_URL": "http://localhost:3021",
        "BOT_PUBKEY_HEX": "ef7dd16da39491e066e31d2403a2ee51dca07d4e2a58bd1ce98c1c848193b992",
        "BOT_NPUB": "npub1aa7azmdrjjg7qehrr5jq8ghw28w2ql2w9fvt688f3swgfqvnhxfqfu9jrr",
        "USER_NPUB": "npub1qkntvygrrxkc3ynfzw56aq8far9wnxcfjd8d4lfwhnnlnctn4k5sa2d05s",
        "WINGMAN_GITEA_OWNER": "wm21",
        "WINGMAN_GITEA_TOKEN": "417ccffdca0026ca67c63ae0861676b1b229c758",
        "GIT_CONFIG_COUNT": "1",
        "GIT_CONFIG_KEY_0": "credential.https://gitea.pages.otherstuff.ai.helper",
        "GIT_CONFIG_VALUE_0": "/home/pw21/code/wingman/data/gitea-credential-helper.sh",
        "GIT_AUTHOR_NAME": "wm21",
        "GIT_AUTHOR_EMAIL": "wm21@wingman-os.ai",
        "GIT_COMMITTER_NAME": "wm21",
        "GIT_COMMITTER_EMAIL": "wm21@wingman-os.ai"
      },
      "out_file": "/home/pw21/wingman/swift-zinnia-forge/off-piste-studio/apps/logs/swift-zinnia-forge-editing-off-piste-studio-6a5c384e-out.log",
      "error_file": "/home/pw21/wingman/swift-zinnia-forge/off-piste-studio/apps/logs/swift-zinnia-forge-editing-off-piste-studio-6a5c384e-error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs": true,
      "autorestart": false,
      "max_restarts": 0,
      "min_uptime": "5s"
    },
    {
      "name": "swift-zinnia-forge-editing-off-piste-studio-27fdc6f1",
      "namespace": "wingman-agents",
      "script": "bash",
      "args": [
        "-lc",
        "unset OPENAI_BASE_URL OPENAI_API_KEY CODEX_API_KEY ANTHROPIC_BASE_URL ANTHROPIC_API_KEY OPENROUTER_HOST OPENROUTER_API_KEY GOOSE_PROVIDER; exec '/home/pw21/code/wingman/out/agentapi' 'server' '--port' '3705' '--allowed-origins' '*' '--allowed-hosts' 'localhost,127.0.0.1,[::1],dev.otherstuff.studio,dev.otherstuff.ai' '--' 'claude' < /dev/null"
      ],
      "cwd": "/home/pw21/wingman/swift-zinnia-forge/off-piste-studio",
      "env": {
        "SESSION_ID": "27fdc6f1-4030-4314-a2db-a43e75a47064",
        "SESSION_NAME": "editing Off Piste Studio",
        "SESSION_PORT": "3705",
        "SESSION_DIRECTORY": "/home/pw21/wingman/swift-zinnia-forge/off-piste-studio",
        "SESSION_AGENT": "claude",
        "USER_ALIAS": "swift-zinnia-forge",
        "WINGMAN_URL": "http://localhost:3021",
        "BOT_PUBKEY_HEX": "ef7dd16da39491e066e31d2403a2ee51dca07d4e2a58bd1ce98c1c848193b992",
        "BOT_NPUB": "npub1aa7azmdrjjg7qehrr5jq8ghw28w2ql2w9fvt688f3swgfqvnhxfqfu9jrr",
        "USER_NPUB": "npub1qkntvygrrxkc3ynfzw56aq8far9wnxcfjd8d4lfwhnnlnctn4k5sa2d05s",
        "WINGMAN_GITEA_OWNER": "wm21",
        "WINGMAN_GITEA_TOKEN": "417ccffdca0026ca67c63ae0861676b1b229c758",
        "GIT_CONFIG_COUNT": "1",
        "GIT_CONFIG_KEY_0": "credential.https://gitea.pages.otherstuff.ai.helper",
        "GIT_CONFIG_VALUE_0": "/home/pw21/code/wingman/data/gitea-credential-helper.sh",
        "GIT_AUTHOR_NAME": "wm21",
        "GIT_AUTHOR_EMAIL": "wm21@wingman-os.ai",
        "GIT_COMMITTER_NAME": "wm21",
        "GIT_COMMITTER_EMAIL": "wm21@wingman-os.ai"
      },
      "out_file": "/home/pw21/wingman/swift-zinnia-forge/off-piste-studio/apps/logs/swift-zinnia-forge-editing-off-piste-studio-27fdc6f1-out.log",
      "error_file": "/home/pw21/wingman/swift-zinnia-forge/off-piste-studio/apps/logs/swift-zinnia-forge-editing-off-piste-studio-27fdc6f1-error.log",
      "log_date_format": "YYYY-MM-DD HH:mm:ss",
      "merge_logs": true,
      "autorestart": false,
      "max_restarts": 0,
      "min_uptime": "5s"
    }
  ]
};
